import { pgEnum } from "drizzle-orm/pg-core"

export const userRoleEnum = pgEnum("user_role", ["READER", "CURATOR", "ADMIN"])
export const userStatusEnum = pgEnum("user_status", ["ACTIVE", "SUSPENDED", "BANNED"])
export const novelStatusEnum = pgEnum("novel_status", ["ONGOING", "COMPLETED", "HIATUS", "DROPPED"])
export const originalLanguageEnum = pgEnum("original_language", ["VI", "ZH", "KO", "JA", "EN"])
export const chapterStatusEnum = pgEnum("chapter_status", ["DRAFT", "SCHEDULED", "PUBLISHED"])
export const libraryStatusEnum = pgEnum("library_status", ["READING", "COMPLETED", "ON_HOLD", "PLAN_TO_READ"])
export const voteTypeEnum = pgEnum("vote_type", ["UP", "DOWN"])
export const reportTargetTypeEnum = pgEnum("report_target_type", ["COMMENT", "REVIEW", "CHAPTER", "USER"])
export const reportStatusEnum = pgEnum("report_status", ["PENDING", "RESOLVED", "DISMISSED"])
export const paymentMethodEnum = pgEnum("payment_method", ["MOMO", "VNPAY", "CARD"])
export const paymentTypeEnum = pgEnum("payment_type", ["COIN_PURCHASE", "SUBSCRIPTION"])
export const paymentStatusEnum = pgEnum("payment_status", ["PENDING", "SUCCESS", "FAILED", "REFUNDED"])
export const coinTransactionTypeEnum = pgEnum("coin_transaction_type", ["PURCHASE", "UNLOCK", "BONUS", "REFUND"])
export const subscriptionPlanEnum = pgEnum("subscription_plan", ["MONTHLY", "YEARLY"])
export const subscriptionStatusEnum = pgEnum("subscription_status", ["ACTIVE", "CANCELLED", "EXPIRED"])
export const notificationTypeEnum = pgEnum("notification_type", ["NEW_CHAPTER", "SYSTEM"])
export const notificationReferenceTypeEnum = pgEnum("notification_reference_type", ["NOVEL", "CHAPTER"])
